# version: "3.9"  # optional
services:
  nginx:
    restart: always
    build:
      dockerfile: Dockerfile
      context: ./services/nginx
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - ./services/nginx/default.conf:/etc/nginx/conf.d/default.conf
  frontend:
    build:
      dockerfile: Dockerfile
      context: ./services/frontend/
    volumes:
      - /usr/src/app/node_modules
      - ./services/frontend/app:/usr/src/app
